### ISSUE TITLE
Bioc2019 deadline tracker

### ISSUE THREAD

**Issue by kevinrue** [kevinrue/Bioc2019-iSEE-workshop#3]
- [x] May 27: initial draft of workshop, as the vignette of a stand-alone R package in your own GitHub repo. The workshop does not have to be complete, but it be installable. This deadline allows us to start arranging the book and to begin the testing period. Contributors should test their own workshops against bioc-devel; we will provide instructions for using Travis-CI to do this automatically in case you're not familiar with doing this.

- [x] June 10: complete workshop submitted. Only bugfixes / refinements should be made after this point.

- [x] June 17: All workshops complete and building without error. No new commits to contributor repos will be incorporated.
